#!/usr/bin/env python3


num_a = int(input())
a_list = list(map(int,input().split()))
a_list.sort(reverse=True)
              
num_b = int(input())
b_list = list(map(int,input().split()))
b_list.sort(reverse=True)
              
while(len(b_list)):
    if (len(a_list) == 0):
        for b in b_list:
            print(b,end=" ")
        break
    x = a_list.pop()
    y = b_list.pop()

    if x == y:
        continue
        
    while (y < x):
        print(y,end=" ")
        y = b_list.pop()

